const patients=[
 {name:'Meera Kulkarni',id:'NIR-RJ-2026-002184',phone:'DH Kota · +91 98765 43210',age:'42 yrs · Female',last:'Today, 09:54 AM',initials:'MK',status:'In consultation',priority:'High',reason:'Fever & sore throat',arrival:'09:54 AM',token:'GM-12'},
 {name:'Ramesh Iyer',id:'NIR-RJ-2026-001097',phone:'CHC Ramganj · +91 98211 55342',age:'58 yrs · Male',last:'Today, 09:41 AM',initials:'RI',status:'Waiting',priority:'Medium',reason:'Diabetes follow-up',arrival:'09:41 AM',token:'GM-13'},
 {name:'Farah Khan',id:'NIR-RJ-2026-002106',phone:'DH Kota · +91 99871 20119',age:'29 yrs · Female',last:'Today, 09:36 AM',initials:'FK',status:'Waiting',priority:'Routine',reason:'Migraine',arrival:'09:36 AM',token:'GM-14'},
 {name:'Vikram Joshi',id:'NIR-RJ-2026-001455',phone:'PHC Ladpura · +91 97654 11903',age:'65 yrs · Male',last:'Today, 09:28 AM',initials:'VJ',status:'Waiting',priority:'High',reason:'Shortness of breath',arrival:'09:28 AM',token:'GM-15'},
 {name:'Sunita Patil',id:'NIR-RJ-2026-001883',phone:'DH Kota · +91 98902 76123',age:'37 yrs · Female',last:'Yesterday, 04:20 PM',initials:'SP',status:'Follow-up due',priority:'Routine',reason:'Hypertension review',arrival:'09:15 AM',token:'GM-16'}
];
const queue=document.querySelector('#dashboardQueue');
queue.innerHTML=patients.slice(0,4).map(p=>`<div class="queue-person"><span class="queue-token">${p.token}</span><div><b>${p.name}</b><small>${p.age} · ${p.reason}</small></div><div><small>Arrived</small><b>${p.arrival}</b></div><span class="priority ${p.priority.toLowerCase()}">${p.priority}</span><span class="dots">•••</span></div>`).join('');
function renderPatients(list=patients){document.querySelector('#patientRows').innerHTML=list.map(p=>`<div class="patient-row"><div class="table-patient"><span class="patient-photo">${p.initials}</span><div><b>${p.name}</b><small>${p.age}</small></div></div><span class="table-cell">${p.id}</span><span class="table-cell">${p.phone}</span><span class="table-cell">${p.last}</span><span class="status ${p.status==='In consultation'?'active-status':'inactive-status'}">${p.status}</span><span class="dots">•••</span></div>`).join('')}
renderPatients();
document.querySelector('#queueRows').innerHTML=patients.map(p=>`<div class="queue-row"><span class="queue-token">${p.token}</span><div class="table-patient"><span class="patient-photo">${p.initials}</span><div><b>${p.name}</b><small>${p.id}</small></div></div><span class="table-cell">${p.reason}</span><span class="table-cell">${p.arrival}</span><span class="priority ${p.priority.toLowerCase()}">${p.priority}</span><span class="status ${p.status==='In consultation'?'active-status':'inactive-status'}">${p.status}</span><span class="dots">•••</span></div>`).join('');
const pharmacy=[['Meera Kulkarni','PAT-PUN-002184','Dr. Ananya Sharma','Paracetamol 500 mg','12 tablets','Ready to dispense'],['Arjun Desai','PAT-PUN-001328','Dr. Vikram Rao','Amlodipine 5 mg','30 tablets','Processing'],['Nisha Thomas','PAT-PUN-001967','Dr. Ananya Sharma','Cetirizine 10 mg','10 tablets','Ready to dispense'],['Kunal Shah','PAT-PUN-002011','Dr. R. Menon','ORS sachets','8 sachets','Partial stock']];
document.querySelector('#pharmacyCards').innerHTML=pharmacy.map((p,i)=>`<article class="pharmacy-card"><span class="status ${i===1?'inactive-status':'active-status'}">${p[5].toUpperCase()}</span><h3>${p[0]}</h3><p>${p[1]} · ${p[2]}</p><div class="rx-line"><b>${p[3]}</b><small>${p[4]}</small></div><footer><small>Received ${i+8}:2${i} AM</small><button class="${i===1?'outline-btn':'primary-btn'} dispense">${i===1?'Continue':'Dispense'}</button></footer></article>`).join('');
function switchView(id){document.querySelectorAll('.view').forEach(v=>v.classList.remove('active-view'));document.querySelector('#'+id)?.classList.add('active-view');document.querySelectorAll('.nav-item').forEach(b=>b.classList.toggle('active',b.dataset.view===id));window.scrollTo({top:0,behavior:'smooth'})}
document.querySelectorAll('[data-view]').forEach(b=>b.addEventListener('click',()=>switchView(b.dataset.view)));
document.querySelectorAll('[data-view-link]').forEach(b=>b.addEventListener('click',()=>switchView(b.dataset.viewLink)));
document.querySelector('#patientSearch').addEventListener('input',e=>{let q=e.target.value.toLowerCase();renderPatients(patients.filter(p=>Object.values(p).join(' ').toLowerCase().includes(q)))});
document.querySelector('#globalSearch').addEventListener('keydown',e=>{if(e.key==='Enter'){switchView('patients');document.querySelector('#patientSearch').value=e.target.value;document.querySelector('#patientSearch').dispatchEvent(new Event('input'))}});
const modal=document.querySelector('#modal');document.querySelector('#newPatientBtn').onclick=()=>modal.classList.add('show');document.querySelector('#newPatientBtn2').onclick=()=>modal.classList.add('show');document.querySelector('#closeModal').onclick=()=>modal.classList.remove('show');modal.onclick=e=>{if(e.target===modal)modal.classList.remove('show')};
let apiToken='';
async function demoLogin(){try{const r=await fetch('/api/auth/login',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({email:'operator@niramay.demo',password:'Demo@123'})});apiToken=(await r.json()).token||'';}catch(e){console.info('Standalone preview mode');}}
async function api(path,options={}){const r=await fetch(path,{...options,headers:{'Content-Type':'application/json',Authorization:`Bearer ${apiToken}`,...(options.headers||{})}});if(!r.ok)throw new Error((await r.json()).error||'Request failed');return r.json();}
demoLogin();
document.querySelector('#createPatient').onclick=async()=>{const name=document.querySelector('#newName').value||'Kavita Deshmukh';const toast=document.querySelector('#toast');try{if(!apiToken)await demoLogin();const created=await api('/api/patients',{method:'POST',body:JSON.stringify({name,mobile:'',bloodGroup:'Not recorded'})});const token=await api('/api/queue',{method:'POST',body:JSON.stringify({patientId:created.data.id,department:'General Medicine',departmentCode:'GM'})});patients.unshift({name,id:created.data.niramayId,phone:'DH Kota · —',age:'New patient',last:'Just now',initials:name.split(' ').map(x=>x[0]).join('').slice(0,2),status:'Waiting',priority:'Routine',reason:'New registration',arrival:'Now',token:token.data.token});renderPatients();toast.textContent=`Record created · ${created.data.niramayId} · OPD token ${token.data.token}`;}catch(e){patients.unshift({name,id:'NIR-RJ-2026-002191',phone:'DH Kota · —',age:'New patient',last:'Just now',initials:name.split(' ').map(x=>x[0]).join('').slice(0,2),status:'Registered',priority:'Routine',reason:'New registration',arrival:'Now',token:'GM-17'});renderPatients();toast.textContent='Preview record created · NIR-RJ-2026-002191';}modal.classList.remove('show');toast.classList.add('show');setTimeout(()=>toast.classList.remove('show'),4200)};
document.querySelectorAll('.dispense').forEach(b=>b.addEventListener('click',()=>{b.textContent='Dispensed ✓';b.className='outline-btn dispense';b.closest('.pharmacy-card').querySelector('.status').textContent='DISPENSED';b.closest('.pharmacy-card').querySelector('.status').className='status active-status'}));
const governmentScript=document.createElement('script');governmentScript.src='./government.js';document.body.appendChild(governmentScript);
