import React, { useEffect, useMemo, useState } from 'react';
import { Link } from 'react-router-dom';
import { supabase } from '../lib/supabase';

export default function LiveQueue() {
  const [items, setItems] = useState<any[]>([]);
  const [department, setDepartment] = useState('ALL');
  const [search, setSearch] = useState('');
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState('');
  const load = async () => { if (!supabase) { setError('Supabase is not configured. Add your project values in .env.'); setLoading(false); return; } setLoading(true); const result = await supabase.from('queue_tokens').select('*,patients(name,niramay_id),departments(id,name)').order('created_at', { ascending: true }); if (result.error) { console.error(result.error); setError(`Unable to load live queue. Please check your connection and try again. (${result.error.message})`); } else { setItems(result.data || []); setError(''); } setLoading(false); };
  useEffect(() => { load(); if (!supabase) return; const channel = supabase.channel('aarogyavaani-live-queue').on('postgres_changes', { event: '*', schema: 'public', table: 'queue_tokens' }, load).subscribe(); return () => { supabase.removeChannel(channel); }; }, []);
  const departments = Array.from(new Map(items.map(item => [item.departments?.id, item.departments?.name]).filter(([id]) => id)).entries());
  const visible = useMemo(() => items.filter(item => (department === 'ALL' || item.departments?.id === department) && `${item.token} ${item.patients?.name || ''} ${item.patients?.niramay_id || ''}`.toLowerCase().includes(search.toLowerCase())), [items, department, search]);
  const update = async (id: string, status: string) => { if (!supabase) return; const result = await supabase.from('queue_tokens').update({ status, updated_at: new Date().toISOString() }).eq('id', id); if (result.error) setError(`Unable to update queue status. ${result.error.message}`); else await load(); };
  const current = visible.find(item => item.status === 'IN_CONSULTATION');
  return <div><div className="page-head"><div><p className="eyebrow">LIVE OPERATIONS · SUPABASE REALTIME</p><h1>Live queue</h1><p>Every token and status below is read from the connected queue table.</p></div><button className="button" onClick={load}>Refresh</button></div>{error && <div className="error-panel"><span>{error}</span><button onClick={load}>Retry</button></div>}<section className="queue-toolbar"><input value={search} onChange={event => setSearch(event.target.value)} placeholder="Search token, patient or ID" /><select value={department} onChange={event => setDepartment(event.target.value)}><option value="ALL">All departments</option>{departments.map(([id, name]) => <option key={String(id)} value={String(id)}>{String(name)}</option>)}</select></section>{loading ? <div className="state">Loading live queue…</div> : !visible.length ? <div className="empty-panel"><h2>No queue tokens found</h2><p>Register an OPD visit to create a real queue token.</p><Link className="button" to="/opd/register">Open OPD registration</Link></div> : <section className="panel queue-board"><div className="queue-now"><small>NOW IN CONSULTATION</small><b>{current?.token || '—'}</b><span>{current?.patients?.name || 'No patient currently in consultation'}</span></div>{visible.map((item, index) => <div className="queue-item" key={item.id}><b>{index + 1}</b><strong>{item.token}</strong><span>{item.patients?.name || 'Patient'}</span><span>{item.departments?.name || 'Department'}</span><span className={`status-badge ${String(item.status).toLowerCase()}`}>{item.status}</span><div className="queue-actions"><button onClick={() => update(item.id, 'CALLED')}>Call</button><button onClick={() => update(item.id, 'IN_CONSULTATION')}>Start</button><button onClick={() => update(item.id, 'ON_HOLD')}>Hold</button><button onClick={() => update(item.id, 'COMPLETED')}>Complete</button></div></div>)}</section>}</div>;
}
